### ISSUE TITLE
Support for kcachegrind?

### ISSUE THREAD

**Issue by eras** [copy/rmp#1]
Cool!

I wonder, might it be possible to support https://kcachegrind.github.io/ at some point?

**Comment by copy** [comment]
There's a tool to convert from the cpuprofile format to the callgrind format: https://github.com/jlfwong/chrome2calltree, can you check if it works?

It looks relatively simple, it probably wouldn't be much work to add support for this format.

**Comment by copy** [comment]
I went ahead and test it, and it works. Very cool program, I'll integrate this format into rmp.

![tree](https://cloud.githubusercontent.com/assets/1816456/18797324/c3c4c89a-81cd-11e6-943a-f845d503cc07.png)

**Comment by copy** [comment]
Support for kcachegrind is now implemented. Please try it and let me know how it works for you.
